#!/usr/bin/env bash

#  execute the test -- you would most likely execute on submitted file
#  for example: cppcheck ../student_file.h <options>
cppcheck test.cpp ../PC1.h ../PC1.cpp ../common.h ../redirect_iostream.h -x c++ --enable=all --error-exitcode=1 --verbose --suppressions-list=suppressions.txt